urls.py
from django.conf.urls.defaults import *
from wggateway import views
from wggateway.views import DetailViewLocked, ListViewLocked, TemplateViewLocked
from wggateway.models import Client, GroupOfPeople, Sipp, Product, Purchase, ProductProvider, Syndicate
from django.contrib.auth.views import login
from djangorestframework.resources import ModelResource
from djangorestframework.views import ListOrCreateModelView, InstanceModelView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

class ClientResource(ModelResource):
    model = Client

urlpatterns = patterns('',
    # Example:
    # (r'^wggateway/', include('wggateway.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),

    url(r'^$', TemplateViewLocked.as_view(template_name="home.html"), name="home"),
    #url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^clients/(?P<page>[0-9]*)$', ListViewLocked.as_view(
        queryset=Client.objects.all().select_subclasses(),
        context_object_name="client_list",
        template_name="client_list.html",
        paginate_by=25,
        ), name="clients"),
    url(r'^clients/people/(?P<page>[0-9]*)$', ListViewLocked.as_view(
        queryset=GroupOfPeople.objects.all(),
        context_object_name="client_list",
        template_name="client_list.html",
        paginate_by=25,
        ), name="clients_people"),
    url(r'^clients/sipps/(?P<page>[0-9]*)$', ListViewLocked.as_view(
        queryset=Sipp.objects.all(),
        context_object_name="client_list",
        template_name="client_list.html",
        paginate_by=25,
        ), name="clients_sipps"),
    url(r'^clients/other/(?P<page>[0-9]*)$', ListViewLocked.as_view(
        queryset=filter((lambda x: not isinstance(x, GroupOfPeople) and not isinstance(x, Sipp)), Client.objects.all().select_subclasses()),
        context_object_name="client_list",
        template_name="client_list.html",
        paginate_by=25,
        ), name="clients_other"),
    url(r'^client/(?P<pk>\w+)/$', DetailViewLocked.as_view(
        queryset=Client.objects.all().select_subclasses(),
        context_object_name="client",
        template_name="client_detail.html",
        ), name="client"),
    url(r'^clientsearch/$', views.clientsearch),
    url(r'^products/(?P<page>[0-9]*)$', ListViewLocked.as_view(
        queryset=Product.objects.all(),
        template_name="product_list.html",
        paginate_by=25,
        ), name="products"),
    url(r'^product/(?P<pk>\w+)/$', DetailViewLocked.as_view(
        queryset=Product.objects.all(),
        template_name="product_detail.html",
        ), name="product"),
    url(r'^product_provider/(?P<pk>\w+)/$', DetailViewLocked.as_view(
        queryset=ProductProvider.objects.all(),
        template_name="product_provider_detail.html",
        ), name="product_provider"),
    url(r'^purchases/(?P<page>[0-9]*)$', ListViewLocked.as_view(
        queryset=Purchase.objects.all(),
        template_name="purchase_list.html",
        paginate_by=25,
        ), name="purchases"),
    url(r'^purchase/(?P<pk>\w+)/$', DetailViewLocked.as_view(
        queryset=Purchase.objects.all(),
        template_name="purchase_detail.html",
        ), name="purchase"),
    url(r'^syndicates/(?P<page>[0-9]*)$', ListViewLocked.as_view(
        queryset=Syndicate.objects.all(),
        template_name="syndicate_list.html",
        paginate_by=25,
        ), name="syndicates"),
    url(r'^syndicate/(?P<pk>\w+)/$', DetailViewLocked.as_view(
        queryset=Syndicate.objects.all(),
        template_name="syndicate_detail.html",
        ), name="syndicate"),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'admin/login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name="logout"),
    url(r'^accounts/$', 'django.views.generic.simple.redirect_to', {'url': 'login/'}),
    url(r'^accounts/profile/$', 'django.views.generic.simple.redirect_to', {'url': '/'}),
    url(r'^api/clients/$', ListOrCreateModelView.as_view(resource=ClientResource)),
    url(r'^api/client/(?P<pk>[^/]+)/$', InstanceModelView.as_view(resource=ClientResource)),
)

wggateway/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models
from django.db.models import Sum
from model_utils.managers import InheritanceManager
from smart_selects.db_fields import ChainedForeignKey
import locale
from django.core import urlresolvers
import datetime

class AddressBase(models.Model):
    TYPE_CHOICES = (
        ('personal', 'Personal'),
        ('business', 'Business'),
    )
    type = models.CharField(max_length=8, choices=TYPE_CHOICES)
    address1 = models.CharField(max_length=384)
    address2 = models.CharField(max_length=384, blank=True)
    address3 = models.CharField(max_length=384, blank=True)
    city = models.CharField(max_length=384)
    county = models.CharField(max_length=384, blank=True)
    postcode = models.CharField(max_length=30)
    COUNTRY_CHOICES = (
        ('UK', 'United Kingdom'),
        ('US', 'United States'),
    )
    country = models.CharField(max_length=3, choices=COUNTRY_CHOICES)
    phone1 = models.CharField(max_length=32, blank=True)
    phone2 = models.CharField(max_length=32, blank=True)
    email1 = models.EmailField(blank=True)
    email2 = models.EmailField(blank=True)

    def get_details(self):
        return [("Address", self.address1),
                ("", self.address2),
                ("", self.address3),
                ("", self.city),
                ("", self.county),
                ("", self.postcode),
                ("", self.country),
                ]

    def __unicode__(self):
        return u'%s, %s' % (self.postcode, self.address1)

    class Meta:
        abstract = True

class Address(AddressBase):

    class Meta:
        verbose_name_plural="addresses"

class Client(models.Model):
    code = models.CharField(max_length=18, unique=True)
    #address = models.ForeignKey(Address)
    #address = models.OneToOneField(ClientAddress)
    objects = InheritanceManager()

    def get_description(self):
        return "Generic client object, no type assigned"

    def __unicode__(self):
        return self.code

    def get_absolute_url(self):
        return "/client/%i/" % self.id

    def get_admin_change_url(self):
        return urlresolvers.reverse('admin:wggateway_client_change', args=(self.id,))

    def get_type(self):
        return self.__class__.__name__

class ClientAddress(AddressBase):
    client = models.OneToOneField(Client, primary_key=True)

    class Meta:
        verbose_name_plural="client addresses"

class OldAddress(AddressBase):
    client = models.ForeignKey(Client)
    deprication_date = models.DateField()

    def __unicode__(self):
        return u'%s, %s' % (self.postcode, self.address1)

    class Meta:
        verbose_name_plural="old addresses"

class Person(models.Model):
    title = models.CharField(max_length=48)
    firstname = models.CharField(max_length=192)
    middlename = models.CharField(max_length=192, blank=True)
    lastname = models.CharField(max_length=192)

    def get_readable_name(self):
        return self.title + ". " + self.firstname + " " + self.lastname

    def __unicode__(self):
        return u'%s, %s' % (self.lastname, self.firstname)

    class Meta:
        verbose_name_plural="people"

class GroupOfPeople(Client):
    people = models.ManyToManyField(Person, blank=True)

    def get_names(self):
        names=[]
        for person in self.people.all():
            names.append(person.get_readable_name())
        return names

    def get_description(self):
        names=self.get_names()
        return ', '.join(names)

    def get_details(self):
        return [("ClientCode", self.code),
                ("Type", self.get_type),
                ("People", self.get_description)] + self.address.get_details()

    def get_admin_change_url(self):
        return urlresolvers.reverse('admin:wggateway_groupofpeople_change', args=(self.id,))

    def __unicode__(self):
        return self.code

    class Meta:
        verbose_name_plural="groups of people"

class SippProvider(models.Model):
    name = models.CharField(max_length=384)

    def __unicode__(self):
        return self.name

class SippAdminPerson(models.Model):
    company = models.ForeignKey(SippProvider)
    title = models.CharField(max_length=48)
    firstname = models.CharField(max_length=192)
    middlename = models.CharField(max_length=192, blank=True)
    lastname = models.CharField(max_length=192)

    def __unicode__(self):
        return u'%s %s' % (self.firstname, self.lastname)

    class Meta:
        verbose_name_plural="sipp admin people"

class SippAdminPersonAddress(AddressBase):
    sippadminperson = models.OneToOneField(SippAdminPerson, primary_key=True)

    class Meta:
        verbose_name_plural="admin person addresses"

class Sipp(Client):
    company = models.ForeignKey(SippProvider)
    reference = models.CharField(max_length=64)
    admin_person = ChainedForeignKey(
            SippAdminPerson,
            chained_field="company",
            chained_model_field="company", 
            show_all=False, 
            auto_choose=True
            )

    def get_admin_change_url(self):
        return urlresolvers.reverse('admin:wggateway_sipp_change', args=(self.id,))

    def get_description(self):
        return self.company.name + ": " + self.reference

    def get_details(self):
        return [("ClientCode", self.code),
                ("Type", self.get_type),
                ("Provider", self.company),
                ("Reference", self.reference),
                ("Admin Person", self.admin_person)] + self.address.get_details()

    def __unicode__(self):
        return u'%s %s' % (self.company, self.reference)

class LLC(Client):
    name = models.CharField(max_length=64)

    def get_admin_change_url(self):
        return urlresolvers.reverse('admin:wggateway_llc_change', args=(self.id,))

    def __unicode__(self):
        return u'%s' % (self.name)

class Syndicate(models.Model):
    name = models.CharField(max_length=32)

    def get_absolute_url(self):
        return "/syndicate/%i/" % self.id

    def get_admin_change_url(self):
        return urlresolvers.reverse('admin:wggateway_syndicate_change', args=(self.id,))

    def __unicode__(self):
        return self.name

class ProductProvider(models.Model):
    name = models.CharField(max_length=64)

    def get_purchase_count(self):
        #return Purchase.objects.filter(product__provider__id = self.id).count()
        return self.get_purchases().count()

    def get_purchases(self):
        return Purchase.objects.filter(product__provider__id = self.id, active=1)

    def get_returns(self):
        """
        Returns an ordered list of pairs, where each pair is made up of a date and a dictionary, and each dictionary has currencies as its keys and amounts as its values
        """
        dated_returns = {}
        for rent in Rent.objects.filter(purchase__product__id = self.id):
            if rent.due_date not in dated_returns:
                dated_returns[rent.due_date] = {}
            for currency, amount in rent.get_total_amounts():
                if currency not in dated_returns[rent.due_date]:
                    dated_returns[rent.due_date][currency] = 0
                dated_returns[rent.due_date][currency] += amount
        dated_returns_list=dated_returns.items()
        dated_returns_list.sort()
        return dated_returns_list

    def get_invested_currencies(self):
        """
        Returns the set of currencies that have ever been the notional currency of a purchase of a product issued by this provider
        """
        return Currency.objects.filter(purchase_notional_currency__product__provider__id = self.id)

    def get_amounts_invested(self):
        """
        Currently broken... doesn't match prototype.
        """
        currency_amounts={}
        for currency in self.get_invested_currencies():
            currency_amounts[currency.code] = self.get_purchases().filter(notional_currency__code=currency.code).aggregate(Sum('notional'))['notional__sum']
        return currency_amounts

    def get_absolute_url(self):
        return "/product_provider/%i/" % self.id

    def __unicode__(self):
        return self.name

class Product(models.Model):
    provider = models.ForeignKey(ProductProvider)
    name = models.CharField(max_length=64)
    prefix = models.CharField(max_length=6)
    increment = models.IntegerField()
    display_order = models.IntegerField()

    def get_absolute_url(self):
        return "/product/%i/" % self.id

    def get_active_purchases(self):
        return self.purchase_set.filter(active=1)

    def get_inactive_purchases(self):
        return self.purchase_set.filter(active=0)

    def get_invested_currencies(self):
        return Currency.objects.filter(purchase_notional_currency__product__id = self.id)

    def get_amounts_invested(self):
        currency_amounts={}
        for currency in self.get_invested_currencies():
            currency_amounts[currency.code] = self.purchase_set.filter(notional_currency__code=currency.code, active=1).aggregate(Sum('notional'))['notional__sum']
        return currency_amounts

    def get_returns(self):
        """
        Returns an ordered list of pairs, where each pair is made up of a date and a dictionary, and each dictionary has currencies as its keys and amounts as its values
        """
        dated_returns = {}
        for rent in Rent.objects.filter(purchase__product__id = self.id):
            if rent.due_date not in dated_returns:
                dated_returns[rent.due_date] = {}
            for currency, amount in rent.get_total_amounts():

wggateway/forms.py
from django import forms
from models import Product

class ContactForm(forms.Form):
    subject = forms.CharField()
    message = forms.CharField()
    email = forms.EmailField(required=False)

class ClientSearchForm(forms.Form):
    client_code = forms.CharField(required=False)
    #commented because it doesn't make much sense since a client can be a sipp with no name field
    #name = forms.CharField(required=False)
    post_code = forms.CharField(required=False)
    email = forms.CharField(required=False)

#class ProductForm(forms.ModelForm):
    #class Meta:
        #model = Product

wggateway/views.py
from django.shortcuts import render_to_response
from django.db.models import Q
from models import Client
from forms import ClientSearchForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, TemplateView

@login_required
def clientsearch(request):
    if request.method == 'POST':
        form = ClientSearchForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if (cd['post_code'] != '' or cd['email'] != ''):
                clients=Client.objects.filter(
                        Q(code__icontains=cd['client_code']),
                        Q(address__postcode__icontains=cd['post_code']),
                        Q(address__email1__icontains=cd['email'])|
                        Q(address__email2__icontains=cd['email']))
            else:
                clients=Client.objects.filter(
                        Q(code__icontains=cd['client_code']))
            return render_to_response('search_results.html',
                    { 'client_list': clients.select_subclasses() })
    else:
        form = ClientSearchForm()
    return render_to_response('search_form.html', {'form': form})

class DetailViewLocked(DetailView):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DetailViewLocked, self).dispatch(*args, **kwargs)

class ListViewLocked(ListView):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ListViewLocked, self).dispatch(*args, **kwargs)

class TemplateViewLocked(TemplateView):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TemplateViewLocked, self).dispatch(*args, **kwargs)

wggateway/templates/base.html
{% block doctype %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
{% endblock %}

<html xmlns="http://www.w3.org/1999/xhtml" lang="en-uk" xml:lang="en-uk" > 
    <head>
        <title>
            {% block title %}{% endblock %}
        </title>
        {% load static %}
        <link rel="stylesheet" href="{% get_static_prefix %}layout.css" type="text/css">
        <link rel="stylesheet" href="{% get_static_prefix %}style2.css" type="text/css">
        {% block extrahead %}{% endblock %}
    </head>

    <body>
        <div id="wrap">
            <div id="main">
                <div id="navcontainer"> 
                    {% block sidenav %}
                    {% include "sidenav.html" %}
                    {% block subsidenav %}
                    {% endblock subsidenav %}
                    {% endblock sidenav %}
                </div>

                <div id="content">
                    {% block content %}{% endblock %}
                </div>

                <div id="pagination">
                    {% block pagination %}{% endblock %}
                </div>
            </div>
        </div>

        <div id="footer">
            {% block footer %}
            Powerscourt Services - Enabling investments in overseas property.
            {% endblock %}
        </div>
    </body>
</html>

wggateway/templates/group_detail.html
{% extends "base.html" %}
{% block title %}Group Of Peoeple Detail{% endblock %}
{% block content %}
    <h1>Group Of Peoeple Detail</h1>
    <p>{{ object.code }} is of type {{ object.get_type }}</p>
{% endblock %}

wggateway/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>
{% endblock %}

wggateway/templates/product.html
{% extends "base.html" %}
{% block subsidenav %}
<ul id="subnavlist"> 
    <li><a href="{% url products page=1 %}">All Products</a></li> 
</ul> 
{% endblock %}

wggateway/templates/product_detail.html
{% extends "product.html" %}
{% load humanize %}
{% block title %}Product Detail{% endblock %}
{% block content %}

<h1>Product Detail</h1>
<div class="formrow"><div class="formlabel2">Name</div> <div class="formfield">{{ product.name }}</div>
    <div class="formlabel2"><a href="{% url admin:wggateway_product_change product.id %}">Edit</a></div>
</div>
<div class="formrow"><div class="formlabel2">Provider</div> <div class="formfield"><a href={% url product_provider pk=product.provider.id %}>{{ product.provider.name }}</a></div>
    <div class="formlabel2"><a href="{% url admin:wggateway_productprovider_change product.provider.id %}">Edit</a></div>
</div>
<div class="formrow"><div class="formlabel2">Prefix</div> <div class="formfield">{{ product.prefix }}</div></div>
<div class="formrow"><div class="formlabel2">Increment</div> <div class="formfield">{{ product.increment }}</div></div>
<div class="formrow"><div class="formlabel2">Display Order</div> <div class="formfield">{{ product.display_order }}</div></div>

<div class="formheaderrow">
    <div class="formheadercell">Amount invested</div>
</div>
<div class="formrow">
    <div class="formlabel2"></div>
    {% for currency, amount in product.get_amounts_invested.items %}
    <div class="formamount">{{ currency }} {{ amount|intcomma }}</div>
    {% endfor %}
</div>

<div class="formheaderrow">
    <div class="formheadercell">Returns</div>
</div>
{% for returndate, currencies in product.get_returns %}
<div class="formrow">
    <div class="formlabel2">{{ returndate|date:"SHORT_DATE_FORMAT" }}</div>
    {% for currency, amount in currencies.items %}
    <div class="formamount">{{ currency }} {{ amount|intcomma }}</div>
    {% endfor %}
</div>
{% endfor %}

<div class="formheaderrow">
    <div class="formheadercell">Total future payments</div>
</div>
<div class="formrow">
    <div class="formlabel2"></div>
    {% for currency, amount in product.get_total_future_returns %}
    <div class="formamount">{{ currency }} {{ amount|intcomma }}</div>
    {% endfor %}
</div>

<div class="formheaderrow">
    <div class="formheadercell">Purchases/Clients (current)</div>
</div>
{% for purchase in product.get_active_purchases %}
<div class="formrow">
    <div class="formlabel2"><a href={% url purchase pk=purchase.id %}>{{ purchase.code }} {{ purchase.client.code }}</a></div>
    <div class="formlabel2">{{ purchase.notional_currency }} {{ purchase.notional|intcomma }}</div>
    <div class="formfield">{{ purchase.get_client_subclass.get_description }} - {{ purchase.client.clientaddress.email1 }} - {{ purchase.form }}</div>
</div>
{% endfor %}

<div class="formheaderrow">
    <div class="formheadercell">Purchases/Clients (former)</div>
</div>
{% for purchase in product.get_inactive_purchases %}
<div class="formrow">
    <div class="formlabel2"><a href={% url purchase pk=purchase.id %}>{{ purchase.code }} {{ purchase.client.code }}</a></div>
    <div class="formfield">{{ purchase.get_client_subclass.get_description }}</div>
</div>
{% endfor %}

{% endblock %}

wggateway/templates/product_form.html
{% extends "base.html" %}
{% block title %}Add Product{% endblock %}
{% block content %}
    <h1>Add Product</h1>
    {% if form.errors %}
    <p style="color: red;">
    Please correct the error{{ form.errors|pluralize }} below.
    </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

wggateway/templates/product_list.html
{% extends "product.html" %}

{% block title %}Product List{% endblock %}

{% block content %}
<h1>Product List</h1>
{% for product in product_list %}
<div class="formrow">
    <div class="formlabel2">
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
    </div>
    <div class="formfield">
        {{ product.provider }}
    </div>
</div>
{% endfor %}
{% endblock %}

{% block pagination %}
{% include "pagination.html" %}
{% endblock %}

wggateway/templates/product_provider_detail.html
{% extends "product.html" %}
{% load humanize %}
{% block title %}Product Provider Detail{% endblock %}
{% block content %}

<h1>Product Provider Detail</h1>
<div class="formrow"><div class="formlabel2">Provider</div><div class="formfield">{{ productprovider.name }}</div>
    <div class="formlabel2"><a href="{% url admin:wggateway_productprovider_change productprovider.id %}">Edit</a></div>
</div>
<div class="formrow"><div class="formlabel2">No of purchases</div><div class="formfield">{{ productprovider.get_purchase_count }}</div></div>

<div class="formheaderrow">
    <div class="formheadercell">Amount invested</div>
</div>
<div class="formrow">
    <div class="formlabel2"></div>
    {% for currency, amount in productprovider.get_amounts_invested.items %}
    <div class="formamount">{{ currency }} {{ amount|intcomma }}</div>
    {% endfor %}
</div>

{% for product in productprovider.product_set.all %}
<div class="formrow">
    <div class="formlabel2">Product</div>
    <div class="formfield"><a href="{% url product product.id %}">{{ product.name }}</a></div>
</div> 
{% endfor %}

{% endblock %}

wggateway/templates/purchase_list.html
{% extends "purchase.html" %}

{% block title %}Purchase List{% endblock %}

{% block content %}
<h1>Purchase List</h1>
{% for purchase in purchase_list %}
<div class="formrow">
    <div class="formlabel1">
        <a href="{{ purchase.get_absolute_url }}">{{ purchase.code }}</a>
    </div>
    <div class="formfield">
        {{ purchase.client.code }} ({{ purchase.product }}, {{ purchase.product.provider }}, {{ purchase.notional }} {{ purchase.notional_currency.code }})
    </div>
</div>
{% endfor %}
{% endblock %}

{% block pagination %}
{% include "pagination.html" %}
{% endblock %}

wggateway/templates/search_form.html
{% extends "client.html" %}
{% block title %}Client Search{% endblock %}
{% block content %}
    <h1>Client Search</h1>
    {% if form.errors %}
    <p style="color: red;">
    Please correct the error{{ form.errors|pluralize }} below.
    </p>
    {% endif %}

    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

wggateway/templates/search_results.html
{% extends "client.html" %}
{% block title %}Client Search{% endblock %}
{% block content %}
<h1>Client Search Results</h1>
{% if client_list %}
<p>Found {{ client_list|length }} client{{ client_list|pluralize }}.</p>
{% for client in client_list %}
<div class="formrow">
    <div class="formlabel1">
        <a href="{{ client.get_absolute_url }}">{{ client.code }}</a>
    </div>
    <div class="formfield">
        is of type {{ client.get_type }}
    </div>
</div>
{% endfor %}
{% else %}
<p>No client_list matched your search criteria.</p>
{% endif %}
{% endblock %}

wggateway/templates/sidenav.html
<ul id="navlist"> 
    <li><a href="{% url home %}">Home</a></li> 
    <li><a href="{% url wggateway.views.clientsearch %}">Clients</a></li> 
    <li><a href="{% url products page=1 %}">Products</a></li> 
    <li><a href="{% url purchases page=1 %}">Purchases</a></li> 
    <li><a href="{% url syndicates page=1 %}">Syndicates</a></li> 
    <li><a href="">Accounts</a></li> 
    <li><a href="{% url admin:index %}">Admin</a></li> 
    <li><a href="{% url logout %}">Log out</a></li> 
</ul> 

wggateway/templates/syndicate.html
{% extends "base.html" %}
{% block subsidenav %}
<ul id="subnavlist"> 
    <li><a href="{% url syndicates page=1 %}">All Syndicates</a></li> 
</ul> 
{% endblock %}

wggateway/templates/syndicate_detail.html
{% extends "syndicate.html" %}
{% load humanize %}
{% block title %}Syndicate Detail{% endblock %}
{% block content %}
<h1>Syndicate Detail</h1>
<div class="formrow"><div class="formlabel2">Name</div> <div class="formfield">{{ syndicate.name }}</div>
    <div class="formlabel2"><a href="{% url admin:wggateway_syndicate_change syndicate.id %}">Edit</a></div>
</div>
<div class="formrow">
    <div class="formlabel2">Purchases</div>
    <div class="formfieldwide">
        <table class="ps_table"> 
            <tr class="ps_row"> 
                <td class="ps_col">Code</td> 
                <td class="ps_col">Currency</td> 
                <td class="ps_col">Notional</td> 
                <td class="ps_col">Product</td> 
                <td class="ps_col">Provider</td> 
            </tr> 
            {% for purchase in syndicate.purchase_set.all %}
            <tr class="ps_row">
                <td class="ps_col"><a href={% url purchase pk=purchase.id %}>{{ purchase.code }}</a></td>
                <td class="ps_col">{{ purchase.notional_currency }}</td>
                <td class="ps_col">{{ purchase.notional|intcomma }}</td>
                <td class="ps_col">{{ purchase.product }}</td>
                <td class="ps_col">{{ purchase.product.provider }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div> 
{% endblock %}